// <auto-generated />
using System;
using BEERAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BEERAPI.Migrations
{
    [DbContext(typeof(EcommerceDbContext))]
    [Migration("20260329034918_InitialCodeFirst")]
    partial class InitialCodeFirst
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BEERAPI.Models.BankTransaction", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Accumulated")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtractedOrderCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gateway")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OrderID");

                    b.Property<string>("RawJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("SubAccount")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("TransferAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TransferType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__BankTran__3214EC078A315079");

                    b.ToTable("BankTransaction", (string)null);
                });

            modelBuilder.Entity("BEERAPI.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Category__3214EC07C123412E");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("BEERAPI.Models.Logging", b =>
                {
                    b.Property<Guid>("LogUid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LogUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Level")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RecordUid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RecordUID");

                    b.Property<string>("TableName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("UserUid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserUID");

                    b.HasKey("LogUid")
                        .HasName("PK__Logging__D12CCB367042FDA1");

                    b.HasIndex("UserUid");

                    b.ToTable("Logging", (string)null);
                });

            modelBuilder.Entity("BEERAPI.Models.Order", b =>
                {
                    b.Property<Guid>("OrderUid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OrderUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<Guid>("ShopUid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ShopUID");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid?>("Type")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserUid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserUID");

                    b.HasKey("OrderUid")
                        .HasName("PK__Order__EF45ED22EF65FC3F");

                    b.HasIndex("ShopUid");

                    b.HasIndex("UserUid");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("BEERAPI.Models.OrderItem", b =>
                {
                    b.Property<Guid>("OrderItemUid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OrderItemUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("OrderUid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OrderUID");

                    b.Property<Guid>("ProductUid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProductUID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("OrderItemUid")
                        .HasName("PK__OrderIte__7A70AEA3A156B1BD");

                    b.HasIndex("OrderUid");

                    b.HasIndex("ProductUid");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("BEERAPI.Models.Product", b =>
                {
                    b.Property<Guid>("ProductUid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProductUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("Category")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Img")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("PriceConfig")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("ShopUid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ShopUID");

                    b.Property<int?>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ProductUid")
                        .HasName("PK__Product__ADC6EB5B72584E7C");

                    b.HasIndex("Category");

                    b.HasIndex("ShopUid");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("BEERAPI.Models.Shop", b =>
                {
                    b.Property<Guid>("ShopUid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ShopUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Img")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Password")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ShopUid")
                        .HasName("PK__Shop__5DD995CC9AA24EB6");

                    b.ToTable("Shop", (string)null);
                });

            modelBuilder.Entity("BEERAPI.Models.Table", b =>
                {
                    b.Property<Guid>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TableID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OrderID");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("TableId")
                        .HasName("PK__Table__7D5F018E1216FD52");

                    b.ToTable("Table", (string)null);
                });

            modelBuilder.Entity("BEERAPI.Models.User", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Address")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ShopUid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ShopUID");

                    b.HasKey("Uid")
                        .HasName("PK__User__C5B1960282B28074");

                    b.HasIndex("ShopUid");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("BEERAPI.Models.Logging", b =>
                {
                    b.HasOne("BEERAPI.Models.User", "UserU")
                        .WithMany("Loggings")
                        .HasForeignKey("UserUid")
                        .HasConstraintName("FK__Logging__UserUID__71D1E811");

                    b.Navigation("UserU");
                });

            modelBuilder.Entity("BEERAPI.Models.Order", b =>
                {
                    b.HasOne("BEERAPI.Models.Shop", "ShopU")
                        .WithMany("Orders")
                        .HasForeignKey("ShopUid")
                        .IsRequired()
                        .HasConstraintName("FK__Order__ShopUID__656C112C");

                    b.HasOne("BEERAPI.Models.User", "UserU")
                        .WithMany("Orders")
                        .HasForeignKey("UserUid")
                        .HasConstraintName("FK__Order__UserUID__66603565");

                    b.Navigation("ShopU");

                    b.Navigation("UserU");
                });

            modelBuilder.Entity("BEERAPI.Models.OrderItem", b =>
                {
                    b.HasOne("BEERAPI.Models.Order", "OrderU")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderUid")
                        .IsRequired()
                        .HasConstraintName("FK__OrderItem__Order__6A30C649");

                    b.HasOne("BEERAPI.Models.Product", "ProductU")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductUid")
                        .IsRequired();

                    b.Navigation("OrderU");

                    b.Navigation("ProductU");
                });

            modelBuilder.Entity("BEERAPI.Models.Product", b =>
                {
                    b.HasOne("BEERAPI.Models.Category", "CategoryNavigation")
                        .WithMany("Products")
                        .HasForeignKey("Category")
                        .HasConstraintName("FK_Product_Category");

                    b.HasOne("BEERAPI.Models.Shop", "ShopU")
                        .WithMany("Products")
                        .HasForeignKey("ShopUid")
                        .IsRequired()
                        .HasConstraintName("FK__Product__ShopUID__5FB337D6");

                    b.Navigation("CategoryNavigation");

                    b.Navigation("ShopU");
                });

            modelBuilder.Entity("BEERAPI.Models.User", b =>
                {
                    b.HasOne("BEERAPI.Models.Shop", "ShopU")
                        .WithMany("Users")
                        .HasForeignKey("ShopUid")
                        .IsRequired()
                        .HasConstraintName("FK__User__ShopUID__534D60F1");

                    b.Navigation("ShopU");
                });

            modelBuilder.Entity("BEERAPI.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BEERAPI.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BEERAPI.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BEERAPI.Models.Shop", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Products");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BEERAPI.Models.User", b =>
                {
                    b.Navigation("Loggings");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
