// <auto-generated />
using System;
using BEERAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BEERAPI.Migrations
{
    [DbContext(typeof(EcommerceDbContext))]
    partial class EcommerceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BEERAPI.Models.BankTransaction", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_number");

                    b.Property<decimal?>("Accumulated")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("accumulated");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExtractedOrderCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("extracted_order_code");

                    b.Property<string>("Gateway")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gateway");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("RawJson")
                        .HasColumnType("text")
                        .HasColumnName("raw_json");

                    b.Property<string>("ReferenceCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_code");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<string>("SubAccount")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sub_account");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("transaction_date");

                    b.Property<decimal?>("TransferAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("transfer_amount");

                    b.Property<string>("TransferType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("transfer_type");

                    b.HasKey("Id")
                        .HasName("banktransaction_pkey");

                    b.ToTable("bank_transaction", (string)null);
                });

            modelBuilder.Entity("BEERAPI.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("category_pkey");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("BEERAPI.Models.Logging", b =>
                {
                    b.Property<Guid>("LogUid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_uid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Level")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid?>("RecordUid")
                        .HasColumnType("uuid")
                        .HasColumnName("record_uid");

                    b.Property<string>("TableName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("table_name");

                    b.Property<Guid?>("UserUid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uid");

                    b.HasKey("LogUid")
                        .HasName("logging_pkey");

                    b.HasIndex("UserUid");

                    b.ToTable("logging", (string)null);
                });

            modelBuilder.Entity("BEERAPI.Models.Order", b =>
                {
                    b.Property<Guid>("OrderUid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("order_uid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("order_date")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer")
                        .HasColumnName("payment_type");

                    b.Property<Guid>("ShopUid")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_uid");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_amount");

                    b.Property<Guid?>("Type")
                        .HasColumnType("uuid")
                        .HasColumnName("type");

                    b.Property<Guid?>("UserUid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uid");

                    b.HasKey("OrderUid")
                        .HasName("order_pkey");

                    b.HasIndex("ShopUid");

                    b.HasIndex("UserUid");

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("BEERAPI.Models.OrderItem", b =>
                {
                    b.Property<Guid>("OrderItemUid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_uid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrderUid")
                        .HasColumnType("uuid")
                        .HasColumnName("order_uid");

                    b.Property<Guid>("ProductUid")
                        .HasColumnType("uuid")
                        .HasColumnName("product_uid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("OrderItemUid")
                        .HasName("order_item_pkey");

                    b.HasIndex("OrderUid");

                    b.HasIndex("ProductUid");

                    b.ToTable("order_item", (string)null);
                });

            modelBuilder.Entity("BEERAPI.Models.Product", b =>
                {
                    b.Property<Guid>("ProductUid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("product_uid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("Category")
                        .HasColumnType("uuid")
                        .HasColumnName("category");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Img")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("img");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<decimal?>("PriceConfig")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price_config");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("product_name");

                    b.Property<Guid>("ShopUid")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_uid");

                    b.Property<int?>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stock");

                    b.Property<int?>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("type");

                    b.HasKey("ProductUid")
                        .HasName("product_pkey");

                    b.HasIndex("Category");

                    b.HasIndex("ShopUid");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("BEERAPI.Models.Shop", b =>
                {
                    b.Property<Guid>("ShopUid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("shop_uid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Img")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("img");

                    b.Property<string>("Password")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("password");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("shop_name");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("username");

                    b.HasKey("ShopUid")
                        .HasName("shop_pkey");

                    b.ToTable("shop", (string)null);
                });

            modelBuilder.Entity("BEERAPI.Models.Table", b =>
                {
                    b.Property<Guid>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("table_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("TableId")
                        .HasName("table_pkey");

                    b.ToTable("table_info", (string)null);
                });

            modelBuilder.Entity("BEERAPI.Models.User", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<Guid>("ShopUid")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_uid");

                    b.HasKey("Uid")
                        .HasName("user_pkey");

                    b.HasIndex("ShopUid");

                    b.ToTable("user_account", (string)null);
                });

            modelBuilder.Entity("BEERAPI.Models.Logging", b =>
                {
                    b.HasOne("BEERAPI.Models.User", "UserU")
                        .WithMany("Loggings")
                        .HasForeignKey("UserUid")
                        .HasConstraintName("fk_logging_user_uid");

                    b.Navigation("UserU");
                });

            modelBuilder.Entity("BEERAPI.Models.Order", b =>
                {
                    b.HasOne("BEERAPI.Models.Shop", "ShopU")
                        .WithMany("Orders")
                        .HasForeignKey("ShopUid")
                        .IsRequired()
                        .HasConstraintName("fk_order_shop_uid");

                    b.HasOne("BEERAPI.Models.User", "UserU")
                        .WithMany("Orders")
                        .HasForeignKey("UserUid")
                        .HasConstraintName("fk_order_user_uid");

                    b.Navigation("ShopU");

                    b.Navigation("UserU");
                });

            modelBuilder.Entity("BEERAPI.Models.OrderItem", b =>
                {
                    b.HasOne("BEERAPI.Models.Order", "OrderU")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderUid")
                        .IsRequired()
                        .HasConstraintName("fk_order_item_order_uid");

                    b.HasOne("BEERAPI.Models.Product", "ProductU")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductUid")
                        .IsRequired()
                        .HasConstraintName("fk_order_item_product_uid");

                    b.Navigation("OrderU");

                    b.Navigation("ProductU");
                });

            modelBuilder.Entity("BEERAPI.Models.Product", b =>
                {
                    b.HasOne("BEERAPI.Models.Category", "CategoryNavigation")
                        .WithMany("Products")
                        .HasForeignKey("Category")
                        .HasConstraintName("fk_product_category");

                    b.HasOne("BEERAPI.Models.Shop", "ShopU")
                        .WithMany("Products")
                        .HasForeignKey("ShopUid")
                        .IsRequired()
                        .HasConstraintName("fk_product_shop_uid");

                    b.Navigation("CategoryNavigation");

                    b.Navigation("ShopU");
                });

            modelBuilder.Entity("BEERAPI.Models.User", b =>
                {
                    b.HasOne("BEERAPI.Models.Shop", "ShopU")
                        .WithMany("Users")
                        .HasForeignKey("ShopUid")
                        .IsRequired()
                        .HasConstraintName("fk_user_shop_uid");

                    b.Navigation("ShopU");
                });

            modelBuilder.Entity("BEERAPI.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BEERAPI.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BEERAPI.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BEERAPI.Models.Shop", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Products");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BEERAPI.Models.User", b =>
                {
                    b.Navigation("Loggings");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
